config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "works#index"

  resources :works do
    resources :comments, only: [:create, :destroy]
    resources :chats, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end
    patch "/chats/:id", to: "chats#check"
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :work
  has_many   :messages,   dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :work

  validates :content, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1,  name: '--選択してください--' },
    { id: 2,  name: '部屋の掃除' },
    { id: 3,  name: '水回りの掃除' },
    { id: 4,  name: '洗濯' },
    { id: 5,  name: '料理' },
    { id: 6,  name: '買い物' },
    { id: 7,  name: '子守り' },
    { id: 8,  name: 'その他' }
  ]
  end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates :content,   presence: true
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1,  name: '--選択してください--' },
    { id: 2,  name: '手伝って欲しいです！' },
    { id: 3,  name: '手伝います！' }
  ]
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works
  has_many :comments
  has_many :chats
  has_many :messages

  with_options presence: true do
    validates :nickname,   uniqueness:{case_sensitive: false}
    validates :email,      uniqueness: { case_sensitive: false }, format: { with: /@/ }
    validates :password,   length: { minimum: 8 }, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
    validates :tel,        numericality: { only_integer: true, }
  end
end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :type
  belongs_to_active_hash :genre
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :chats,    dependent: :destroy

  with_options presence: true do
    validates :type_id,     numericality: { other_than: 1, message: "が選択されていません" }
    validates :name
    validates :genre_id,    numericality: { other_than: 1, message: "が選択されていません" }
    validates :place
    validates :start_time,  if: :past_date_time
    validates :end_time,    if: :past_start_time
    validates :description
  end

  private
  def past_date_time
    if start_time < Time.current
      errors.add(:start_time, "が正しくありません")
    end
  end

  def past_start_time
    if end_time < start_time || end_time < Time.current
      errors.add(:end_time, "が正しくありません") 
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :tel])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :destroy, :check]
  before_action :move_to_index, only: [:show]

  def create
    @work = Work.find(params[:work_id])
    @chat = Chat.new(chat_params)
    if @chat.save
      redirect_to "/works/#{@work.id}/chats/#{@chat.id}"
    else
      redirect_to "/works/#{@work.id}/chats/#{@chat.id}"
    end
  end

  def show
    @message = Message.new
    @messages = @chat.messages.includes(:user)
  end

  def destroy
    if @chat.destroy
      redirect_to user_path
    else
      redirect_to user_path
    end
  end

    def check
      work_check = Chat.find_by(check: true, work_id: @chat.work_id)
      if !@chat.check && work_check.nil?
      @chat.update(check: true)
      flash[:matcing_notice] = "マッチングが成立しました !"
      redirect_to "/works/#{@work.id}/chats/#{@chat.id}"
      elsif @chat.check
        @chat.update(check: false)
        flash[:matcing_notice] = "マッチングを解除しました"
        redirect_to "/works/#{@work.id}/chats/#{@chat.id}"
      else
        flash[:matcing_notice] = "他の方とマッチング済みです"
        redirect_to "/works/#{@work.id}/chats/#{@chat.id}"
      end
    end

  private

  def chat_params
    params.permit(:work_id, :user_id)
  end

  def set_chat
    @work = Work.find(params[:work_id])
    @chat = Chat.find(params[:id])
  end

  def move_to_index
    if !user_signed_in? || current_user.id != @work.user_id && current_user.id != @chat.user_id
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to  "/works/#{comment.work.id}"
    else
      flash[:comment_error] = "*空欄のためコメントできませんでした*"
      redirect_to  "/works/#{comment.work.id}"
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to "/works/#{comment.work.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, work_id: params[:work_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    work = Work.find(params[:work_id])
    chat = Chat.find(params[:chat_id])
    if message.save
      redirect_to "/works/#{work.id}/chats/#{chat.id}"
    else
      redirect_to "/works/#{work.id}/chats/#{chat.id}"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id, chat_id: params[:chat_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show]

  def show
    @user = current_user.nickname
    @work = current_user.works.order('start_time ASC')
    @works = current_user.works.joins(chats: :user)
    @chat = Chat.where(work_id: @works).order('created_at DESC')
    @chats = Chat.where(user_id: current_user)
  end

  private

  def correct_user
    if !user_signed_in? || current_user.id.to_s != params[:id]
      redirect_to root_path
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :authenticate_user!, only: [:new]

  def index
    @work = Work.order('start_time DESC').includes(:user)
  end
  
  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @work.comments.includes(:user)
    @chat = Chat.new
  end

  def update
    if @work.update(update_params)
      redirect_to work_path
    else
      render :edit
    end
  end

  def destroy
    if @work.destroy
      redirect_to user_path
    else
      render :edit
    end
  end
  
  private
  
  def work_params
    params.require(:work).permit(:type_id, :name, :genre_id, :place, :start_time, :end_time, :description).merge(user_id: current_user.id)
  end
  
  def update_params
    params.require(:work).permit(:type_id, :name, :genre_id, :place, :start_time, :end_time, :description)
  end
  
  def set_work
    @work = Work.find(params[:id])
  end

  def correct_user
    work = Work.find(params[:id])
    if !user_signed_in? || current_user.id != work.user_id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/chats/show.html.erb
<%= render "shared/second-header" %>

<div class="wrapper-chat">
  <% if flash[:matcing_notice] %>
    <div class="matching-notice">
      <%= flash[:matcing_notice] %>
    </div>
  <% end %>
  <div class="chat-work-type"><%= @work.type.name %></div>
  <div class="wrapper-chat-tittle">
    <div class="chat-tittle-left">
      <div class="chat-tittle"><%= @work.name %></div>
      <div class="chat-work-date-time">
      日時: <%= @work.start_time.strftime("%Y/%m/%d") %>  <%= @work.start_time.strftime("%H:%M") %>〜<%= @work.end_time.strftime("%H:%M")%>
      </div>
      <div class="chat-join-users"><%= @work.user.nickname %> と <%= @chat.user.nickname %></div>
      <% work_check = Chat.find_by(check: true, work_id: @chat.work_id) %>
      <% if @chat.check %>
        <div class="chat-matching">マッチング !!</div>
      <% elsif !@chat.check && !work_check.nil? %>
        <div class="chat-already-matching">他の方とマッチング済み</div>
      <% end %>
    </div>
    <div class="chat-tittle-right">
    <% if current_user.id == @work.user_id %>
      <%= link_to raw("マッチング !"), work_chat_path(@work.id, @chat.id), method: :patch, class: "matching-btn" %>
    <% end %>
      <%= link_to raw("チャットを<br>削除する"), work_chat_path(@work.id, @chat.id), method: :delete, class: "chat-delete-btn" %>
    </div>
  </div>
    
  <div class="chat-main", id="scroll-inner">
  <% if @messages %>
    <% @messages.each do |message| %>
      <div class="chat-message">
        <div class="message-upper">
          <div class="message-user-name"><%= message.user.nickname %></div>
          <div class="message-date-time">
            <%= message.created_at.strftime("%Y-%m-%d  %H:%M") %>
          </div>
        </div>
        <div class="message-text"><%= message.content %></div>
      </div>
    <% end %>
  <% end %>
  
  </div>

  <div class="wrapper-chat-input">
    <%= form_with model: [@work, @chat, @message], local: true do |f|%>
      <%= f.text_field :content, autofocus: true, class: "message-input" %>
      <%= f.submit "送信", class: "message-submit" %>
    <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/jobs/new.html.erb
<%= render "shared/second-header" %>

<%= form_with model: @job, url: jobs_path, class: "wrapper-form-body", local: true do |f| %>

<div class="wrapper-form-body">
  <div class="wrapper-form">
    <div class="tittle-bar">
      <h2 class="form-tittle">新規投稿</h2>
    </div>

      <div class="text-field">
        <label class="text-field-label">手伝って欲しい！ / 手伝えます！</label>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"text-field-input"}) %>
      </div>
      <div class="text-field">
        <label class="text-field-label">依頼名</label>
        <%= f.text_field :type, class: "text-field-input" %>
      </div>
      <div class="text-field">
        <label class="text-field-label">場所</label>
        <%= f.text_field :type, class: "text-field-input" %>
      </div>
      <div class="text-field">
        <label class="text-field-label">ジャンル</label>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"text-field-input"}) %>
      </div>
      <div class="text-field">
        <label class="text-field-label">開始時間</label>
        <div class="text-field-input">
          <%= raw sprintf(
            f.datetime_select(
              :start_time,
              use_month_numbers: true,
              start_year: (Date.today.year),
              end_year: (Date.today.year + 1),
              date_separator: '%s',
              datetime_separator: '%s',
              time_separator: '%s'),
              '年', '月', '日', '時') + '分' %>
        </div>
      </div>
      <div class="text-field">
        <label class="text-field-label">終了時間</label>
        <div class="text-field-input">
          <%= raw sprintf(
            f.datetime_select(
              :end_time,
              use_month_numbers: true,
              start_year: (Date.today.year),
              end_year: (Date.today.year + 1),
              date_separator: '%s',
              datetime_separator: '%s',
              time_separator: '%s'),
              '年', '月', '日', '時') + '分' %>
        </div>
      </div>
      <div class="text-field">
        <label class="text-field-label">詳細説明</label>
        <%= f.text_area :type, class: "text-area-input" %>
      </div>

      <%= f.submit "投稿する" ,class:"text-field-btn" %>
    
  </div>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseWorkMatching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <%= link_to "かじマッチ", "#", class: "footer-tittle" %>
  <p class="copyright">Copyright © 2020 かじマッチ All rights reserved.</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header">
    <div class="wrapper-tittle">
      <%= link_to "かじマッチ", root_path, class: "site-tittle" %>
    </div>
    <div class="post">
      <%= link_to "投稿する", new_work_path, class: "post-button" %>
    </div>
    <ul class="user-management">
      <% if user_signed_in? %>
        <li><%= link_to "マイページ", user_path(current_user.id), class: "my-page header-button" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout header-button" %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path , class: "log-in header-button" %></li>
        <li><%= link_to "新規登録", new_user_registration_path, class: "sign-in header-button" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header>
  <div class="header">
    <div class="wrapper-tittle">
      <%= link_to "かじマッチ", root_path, class: "site-tittle" %>
    </div>

    <ul class="user-management">
      <% if user_signed_in? %>
        <li><%= link_to "マイページ", user_path(current_user.id), class: "my-page header-button" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout header-button" %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path , class: "log-in header-button" %></li>
        <li><%= link_to "新規登録", new_user_registration_path, class: "sign-in header-button" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>


<div class="my-page-body">
  <div class="my-page-main">
    <div class="my-page-tittle"><%= @user %>のマイページ</div>
    
    <div class="my-page-list-body">
      <div class="my-page-list-left">
        <div class="wrapper-my-page-chat-lists-tittle">
          <div class="my-page-chat-lists-tittle">やりとり中のチャット</div>
        </div>
        <% count = 0 %>

<%# 自分が投稿について、やりとり中のチャット表示 %>
        <% if @chat %>
          <% @chat.each do |chat| %>
            <% count += 1 %>
            <div class="my-page-chat-lists-body">
              <%= link_to "/works/#{chat.work_id}/chats/#{chat.id}", class: "my-page-chat-link" do %>
              <div class="my-page-work-type"><%= chat.work.type.name %></div>
                <div class="my-page-chat-list-left">
                  <div class="my-page-chat-list">
                    <div class="my-page-chat-list-tittle"><%= chat.work.name %></div>
                    <div class="my-page-chat-list-date-time">
                    日時: <%= chat.work.start_time.strftime("%Y/%m/%d") %>  <%= chat.work.start_time.strftime("%H:%M") %>〜<%= chat.work.end_time.strftime("%H:%M")%>
                    </div>
                    <div class="my-page-chat-list-user-name">希望者 : <%= chat.user.nickname %></div>
                  </div>
                </div>
                <% work_check = Chat.find_by(check: true, work_id: chat.work_id) %>
                <% if chat.check %>
                  <div class="my-page-matching">マッチング !!</div>
                <% elsif !chat.check && !work_check.nil? %>
                    <div class="my-page-already-matching">他の方とマッチング済み</div>
                <% end %>
              <% end %>
              <div class="my-page-chat-list-right">
                <%= link_to "削除する", work_chat_path(chat.work_id, chat.id), method: :delete, class: "my-page-chat-delete" %>
              </div>
            </div>
          <% end %>
        <% end %>

<%# 他の人の投稿について、やりとり中のチャット表示 %>
        <% if @chats %>
          <% @chats.each do |chat| %>
            <% count += 1 %>
            <div class="my-page-chat-lists-body">
              <%= link_to "/works/#{chat.work_id}/chats/#{chat.id}", class: "my-page-chat-link" do %>
              <div class="my-page-work-type"><%= chat.work.type.name %></div>
                <div class="my-page-chat-list-left">
                  <div class="my-page-chat-list">
                    <div class="my-page-chat-list-tittle"><%= chat.work.name %></div>
                    <div class="my-page-chat-list-date-time">
                    日時: <%= chat.work.start_time.strftime("%Y/%m/%d") %>  <%= chat.work.start_time.strftime("%H:%M") %>〜<%= chat.work.end_time.strftime("%H:%M")%>
                    </div>
                    <div class="my-page-chat-list-user-name">依頼者 : <%= chat.work.user.nickname %></div>
                  </div>
                </div>
                <% work_check = Chat.find_by(check: true, work_id: chat.work_id) %>
                <% if chat.check %>
                  <div class="my-page-matching">マッチング !!</div>
                  <% elsif !chat.check && !work_check.nil? %>
                    <div class="my-page-already-matching">他の方とマッチングされました</div>
                <% end %>
              <% end %>
              <div class="my-page-chat-list-right">
                <%= link_to "削除する", work_chat_path(chat.work_id, chat.id), method: :delete, class: "my-page-chat-delete" %>
              </div>
            </div>
          <% end %>
        <% end %>
        <% if count == 0 %>
          <div class="posts-body">
            <p class="post-null">やりとり中のチャットはありません</p>
          </div>
        <% end %>
      </div>

<%# 投稿一覧表示 %>
      <div class="my-page-list-right">
        <div class="wrapper-my-page-work-lists-tittle">
          <div class="my-page-work-lists-tittle">投稿一覧</div>
        </div>
        <% if @work %>
        <% count = 0 %>
          <% @work.each do |work| %>
            <% count += 1 %>
            <div class="my-page-work-lists-body">
              <%= link_to "/works/#{work.id}", class: "my-page-work-link" do %>
              <div class="my-page-work-type"><%= work.type.name %></div>
                <div class="my-page-work-list">
                  <div class="my-page-work-list-tittle"><%= work.name %></div>
                  <div class="my-page-work-list-date-time">
                  日時: <%= work.start_time.strftime("%Y/%m/%d") %>  <%= work.start_time.strftime("%H:%M") %>〜<%= work.end_time.strftime("%H:%M")%>
                  </div>
                </div>
                <% work_check = Chat.find_by(check: true, work_id: work.id) %>
                <% if work_check %>
                  <div class="my-page-matching">マッチング !!</div>
                <% end %>
              <% end %>
              <div class="my-page-work-delete-body">
                <%= link_to "編集する", edit_work_path(work.id),  class: "my-page-work-edit-link" %>
                <%= link_to "削除する", work_path(work.id), method: :delete, class: "my-page-work-delete", data: { confirm: "投稿を削除すると、投稿に関連したチャットも全て削除されます。\n本当に、投稿を削除しますか？" } %>
              </div>
            </div>
          <% end %>
          <% if count == 0 %>
            <div class="posts-body">
              <p class="post-null">現在、投稿はありません</p>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/works/new.html.erb
<%= render "shared/second-header" %>

<%= form_with model: @work, url: works_path, class: "wrapper-form-body", local: true do |f| %>

<div class="wrapper-form-body">
  <div class="wrapper-form">
    <div class="tittle-bar">
      <h2 class="form-tittle">新規投稿</h2>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="text-field">
        <label class="text-field-label">手伝って欲しいです！ / 手伝います！</label>
        <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"text-field-input"}) %>
      </div>
      <div class="text-field">
        <label class="text-field-label">依頼名</label>
        <%= f.text_field :name, class: "text-field-input" %>
      </div>
      <div class="text-field">
        <label class="text-field-label">場所</label>
        <%= f.text_field :place, class: "text-field-input" %>
      </div>
      <div class="text-field">
        <label class="text-field-label">ジャンル</label>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"text-field-input"}) %>
      </div>
      <div class="text-field">
        <label class="text-field-label">開始時間</label>
        <div class="text-field-input">
          <%= raw sprintf(
            f.datetime_select(
              :start_time,
              use_month_numbers: true,
              start_year: (Date.today.year),
              end_year: (Date.today.year + 1),
              minute_step: 15,
              date_separator: '%s',
              datetime_separator: '%s',
              time_separator: '%s'),
              '年', '月', '日', '時') + '分' %>
        </div>
      </div>
      <div class="text-field">
        <label class="text-field-label">終了時間</label>
        <div class="text-field-input">
          <%= raw sprintf(
            f.datetime_select(
              :end_time,
              use_month_numbers: true,
              start_year: (Date.today.year),
              end_year: (Date.today.year + 1),
              minute_step: 15,
              date_separator: '%s',
              datetime_separator: '%s',
              time_separator: '%s'),
              '年', '月', '日', '時') + '分' %>
        </div>
      </div>
      <div class="text-field">
        <label class="text-field-label">詳細説明</label>
        <%= f.text_area :description, class: "text-area-input" %>
      </div>

      <%= f.submit "投稿する" ,class:"text-field-btn" %>
    
  </div>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/works/show.html.erb
<%= render "shared/header" %>


<div class="wrapper-detail-jobs">
  <div class="wrapper-detail-board-tittle">
    <p class="works-detail-tittle"><%= @work.type.name %></p>
  </div>
  
  <div class="works-detail">
    <div class="work-detail-tittle"><%= @work.name %></div>
    <div class="work-detail-user-name"><%= @work.user.nickname %></div>
    <div class="work-detail-wrap">
      <p class="work-detail-key">場所</p>
      <p class="work-detail-value"><%= @work.place %></p>
    </div>
    <div class="work-detail-wrap">
      <p class="work-detail-key">ジャンル</p>
      <p class="work-detail-value"><%= @work.genre.name %></p>
    </div>
    <div class="work-detail-wrap">
      <p class="work-detail-key">日時</p>
      <p class="work-detail-value">
      <%= @work.start_time.strftime("%Y/%m/%d") %>  <%= @work.start_time.strftime("%H:%M") %>〜<%= @work.end_time.strftime("%H:%M")%>
      </p>
    </div>
    <div class="work-detail-wrap">
      <p class="work-detail-key">説明</p>
      <p class="work-detail-value"><%= @work.description %></p>
    </div>
    <% if user_signed_in? && current_user.id == @work.user_id %>
      <div class="work-edit-wrap">
        <%= link_to "投稿を編集する", edit_work_path, class: "work-edit-btn" %>
      </div>
    <% end %>

    <div class="wrapper-comments">
      <p class="comment-heading">コメント</p>

      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comments-list">
            <div class="wrapper-comment">
                <div class="comment-upper">
                  <div class="comment-upper-left">
                    <p class="comment-user-name"><%= comment.user.nickname %></p>
                    <p class="comment-create-time"><%= comment.created_at.strftime("%Y-%m-%d  %H:%M") %></p>
                  </div>

                  <% @chat_find = Chat.find_by(work_id: @work.id, user_id: comment.user_id) %>
                  <div class="comment-upper-right">
                    <% if user_signed_in? && current_user.id == @work.user_id && current_user.id != comment.user_id && @chat_find.nil? %>
                      <div class="comment-chat-create-btn">
                        <%= button_to "連絡する", work_chats_path(@work.id, user_id: comment.user_id), class: "comment-chat-create-content" %>
                      </div>
                    <% elsif user_signed_in? && current_user.id == @work.user_id && !@chat_find.nil? %>
                      <div class="comment-chat-link-btn">
                        <%= link_to "連絡する", work_chat_path(@work, @chat_find), class: "comment-chat-link-content" %>
                      </div>
                    <% elsif user_signed_in? && current_user.id == comment.user_id %>
                      <div class="comment-delete-btn">
                        <%= link_to "削除する", work_comment_path(@work, comment), method: :delete, class: "comment-delete-content" %>
                      </div>
                    <% end %>
                  </div>

                </div>
                <div class="comment-text"><%= comment.content %></div>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class='login-flash-message'>
        <%= flash[:comment_error] %>
      </div>
      <% if user_signed_in? %>
        <%= form_with model: [@work, @comment], class: "comment-form", local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <%= f.text_area :content, placeholder: "コメントする", class: "comment-input-content" %>
        <%= f.submit "コメントする", class: "comment-btn" %>
        <% end %>
      <% else %>
      <div class="comment-form">
        <div><%= link_to "ログインしてコメントする", new_user_session_path, class: "comment-log-in-btn comment-btn"%></div>
      </div>
      <% end %>
    </div>
    
  </div>
</div>

<%= render "shared/footer" %>